services:
  - type: web
    name: video-learning-helper-backend
    env: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: uvicorn app.main_supabase:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY  
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
    healthCheckPath: /health 